import { z } from "zod";

const AttributionResultSchema = z.object({
    source: z.enum(["AI", "Manual"]),
    confidence: z.number().min(0).max(1),
    reason: z.string(),
});

export type AttributionResult = z.infer<typeof AttributionResultSchema>;

export interface AttributionRequest {
    id: string;
    snippet: string;
}

export class AttributionEngine {
    private baseUrl: string;
    private model: string;

    constructor(
        baseUrl = "https://openrouter.ai/api/v1/chat/completions",
        model = "qwen/qwen3-next-80b-a3b-instruct:free"
    ) {
        this.baseUrl = baseUrl;
        this.model = model;
    }

    updateConfig(baseUrl?: string, model?: string) {
        if (baseUrl) this.baseUrl = baseUrl;
        if (model) this.model = model;
    }

    private generatePrompt(snippet: string): string {
        return `Analyze the following code snippet/diff and determine if it was likely generated by an AI (like Copilot, Cursor, etc.) or written manually by a human.
Return the result as a STRICT JSON object with the following structure:
{
  "source": "AI" | "Manual",
  "confidence": number (0-1),
  "reason": "concise explanation"
}

Code:
\"\"\"
${snippet}
\"\"\"

Result:`;
    }

    async attributeSnippet(snippet: string): Promise<AttributionResult> {
        const ANTHROPIC_API_KEY = import.meta.env.VITE_ANTHROPIC_API_KEY || "";
        const OPENROUTER_API_KEY = import.meta.env.VITE_OPENROUTER_API_KEY || "";

        try {
            // Attempt direct Anthropic via proxy if key exists
            if (ANTHROPIC_API_KEY) {
                try {
                    const response = await fetch("/anthropic-api/messages", {
                        method: "POST",
                        headers: {
                            "x-api-key": ANTHROPIC_API_KEY,
                            "anthropic-version": "2023-06-01",
                            "Content-Type": "application/json",
                        },
                        body: JSON.stringify({
                            model: "claude-sonnet-4-6",
                            max_tokens: 512,
                            messages: [{ role: "user", content: this.generatePrompt(snippet) }],
                            temperature: 0.1, // Low temperature for deterministic JSON output
                        }),
                    });

                    if (response.ok) {
                        const data = await response.json();
                        const resultText = data.content?.[0]?.text || "";

                        try {
                            // Extract JSON if it's wrapped in triple backticks or other text
                            const jsonMatch = resultText.match(/\{[\s\S]*\}/);
                            const jsonStr = jsonMatch ? jsonMatch[0] : resultText;
                            const parsed = JSON.parse(jsonStr);
                            return AttributionResultSchema.parse(parsed);
                        } catch (e) {
                            console.error("Failed to parse Anthropic response as JSON:", resultText, e);
                        }
                    }
                } catch (err) {
                    console.error("Anthropic fetch failure, falling back to OpenRouter:", err);
                }
            }

            // Fallback to OpenRouter
            const response = await fetch(this.baseUrl, {
                method: "POST",
                headers: {
                    "Authorization": `Bearer ${OPENROUTER_API_KEY}`,
                    "Content-Type": "application/json",
                    "X-OpenRouter-Title": "AI Code Insights Attribution",
                },
                body: JSON.stringify({
                    model: this.model,
                    messages: [
                        {
                            role: "user",
                            content: this.generatePrompt(snippet),
                        },
                    ],
                    max_tokens: 512,
                }),
            });

            if (!response.ok) {
                throw new Error(`OpenRouter API error: ${response.statusText}`);
            }

            const data = await response.json();
            const resultText = data.choices?.[0]?.message?.content || "";


            // Parse the JSON output from LLM
            try {
                const jsonMatch = resultText.match(/\{[\s\S]*\}/);
                const jsonStr = jsonMatch ? jsonMatch[0] : resultText;
                const parsed = JSON.parse(jsonStr);
                return AttributionResultSchema.parse(parsed);
            } catch (e) {
                console.error("Failed to parse LLM response as JSON:", resultText, e);
                return {
                    source: "Manual",
                    confidence: 0,
                    reason: "Error parsing engine response",
                };
            }
        } catch (error) {
            console.error("Attribution engine failure:", error);
            return {
                source: "Manual",
                confidence: 0,
                reason: "Engine connection failure",
            };
        }
    }

    /**
     * Processes a batch of snippets in parallel with a concurrency limit to avoid overloading the local Ollama instance.
     */
    async attributeBatch(
        requests: AttributionRequest[],
        concurrencyLimit = 3
    ): Promise<Record<string, AttributionResult>> {
        const results: Record<string, AttributionResult> = {};
        const queue = [...requests];

        async function processQueue() {
            while (queue.length > 0) {
                const request = queue.shift();
                if (!request) break;

                try {
                    results[request.id] = await this.attributeSnippet(request.snippet);
                } catch (error) {
                    console.error(`Failed to attribute snippet ${request.id}:`, error);
                    results[request.id] = {
                        source: "Manual",
                        confidence: 0,
                        reason: "Engine failure",
                    };
                }
            }
        }

        // Start workers
        const workers = Array(Math.min(concurrencyLimit, requests.length))
            .fill(null)
            .map(() => processQueue.call(this));

        await Promise.all(workers);
        return results;
    }
}

export const attributionEngine = new AttributionEngine();
